// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: signup.proto

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignupService_DecodeAndVerify_FullMethodName = "/scheduler.SignupService/DecodeAndVerify"
)

// SignupServiceClient is the client API for SignupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This service will send an email at the specified time containing a secret signup link
type SignupServiceClient interface {
	// This process is async by definition, there's no confirmation for when the email is eventually sent (if it is ever sent).
	DecodeAndVerify(ctx context.Context, in *SingupEmailTokenString, opts ...grpc.CallOption) (*SignupEmailToken, error)
}

type signupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignupServiceClient(cc grpc.ClientConnInterface) SignupServiceClient {
	return &signupServiceClient{cc}
}

func (c *signupServiceClient) DecodeAndVerify(ctx context.Context, in *SingupEmailTokenString, opts ...grpc.CallOption) (*SignupEmailToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupEmailToken)
	err := c.cc.Invoke(ctx, SignupService_DecodeAndVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupServiceServer is the server API for SignupService service.
// All implementations must embed UnimplementedSignupServiceServer
// for forward compatibility.
//
// This service will send an email at the specified time containing a secret signup link
type SignupServiceServer interface {
	// This process is async by definition, there's no confirmation for when the email is eventually sent (if it is ever sent).
	DecodeAndVerify(context.Context, *SingupEmailTokenString) (*SignupEmailToken, error)
	mustEmbedUnimplementedSignupServiceServer()
}

// UnimplementedSignupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignupServiceServer struct{}

func (UnimplementedSignupServiceServer) DecodeAndVerify(context.Context, *SingupEmailTokenString) (*SignupEmailToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeAndVerify not implemented")
}
func (UnimplementedSignupServiceServer) mustEmbedUnimplementedSignupServiceServer() {}
func (UnimplementedSignupServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignupServiceServer will
// result in compilation errors.
type UnsafeSignupServiceServer interface {
	mustEmbedUnimplementedSignupServiceServer()
}

func RegisterSignupServiceServer(s grpc.ServiceRegistrar, srv SignupServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignupService_ServiceDesc, srv)
}

func _SignupService_DecodeAndVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingupEmailTokenString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupServiceServer).DecodeAndVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignupService_DecodeAndVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupServiceServer).DecodeAndVerify(ctx, req.(*SingupEmailTokenString))
	}
	return interceptor(ctx, in, info, handler)
}

// SignupService_ServiceDesc is the grpc.ServiceDesc for SignupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.SignupService",
	HandlerType: (*SignupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecodeAndVerify",
			Handler:    _SignupService_DecodeAndVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signup.proto",
}
