// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: signup.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingupEmailTokenString struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base-64 encoded. Includes HMAC for verification
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingupEmailTokenString) Reset() {
	*x = SingupEmailTokenString{}
	mi := &file_signup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingupEmailTokenString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingupEmailTokenString) ProtoMessage() {}

func (x *SingupEmailTokenString) ProtoReflect() protoreflect.Message {
	mi := &file_signup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingupEmailTokenString.ProtoReflect.Descriptor instead.
func (*SingupEmailTokenString) Descriptor() ([]byte, []int) {
	return file_signup_proto_rawDescGZIP(), []int{0}
}

func (x *SingupEmailTokenString) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SignupEmailToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MentirologoId int64                  `protobuf:"varint,1,opt,name=mentirologo_id,json=mentirologoId,proto3" json:"mentirologo_id,omitempty"`
	Mentirologo   string                 `protobuf:"bytes,2,opt,name=mentirologo,proto3" json:"mentirologo,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// In seconds since Unix epoch
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupEmailToken) Reset() {
	*x = SignupEmailToken{}
	mi := &file_signup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupEmailToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupEmailToken) ProtoMessage() {}

func (x *SignupEmailToken) ProtoReflect() protoreflect.Message {
	mi := &file_signup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupEmailToken.ProtoReflect.Descriptor instead.
func (*SignupEmailToken) Descriptor() ([]byte, []int) {
	return file_signup_proto_rawDescGZIP(), []int{1}
}

func (x *SignupEmailToken) GetMentirologoId() int64 {
	if x != nil {
		return x.MentirologoId
	}
	return 0
}

func (x *SignupEmailToken) GetMentirologo() string {
	if x != nil {
		return x.Mentirologo
	}
	return ""
}

func (x *SignupEmailToken) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupEmailToken) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type EmptyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	mi := &file_signup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_signup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_signup_proto_rawDescGZIP(), []int{2}
}

var File_signup_proto protoreflect.FileDescriptor

const file_signup_proto_rawDesc = "" +
	"\n" +
	"\fsignup.proto\x12\tscheduler\".\n" +
	"\x16SingupEmailTokenString\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x8f\x01\n" +
	"\x10SignupEmailToken\x12%\n" +
	"\x0ementirologo_id\x18\x01 \x01(\x03R\rmentirologoId\x12 \n" +
	"\vmentirologo\x18\x02 \x01(\tR\vmentirologo\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\n" +
	"\n" +
	"\bEmptyMsg2b\n" +
	"\rSignupService\x12Q\n" +
	"\x0fDecodeAndVerify\x12!.scheduler.SingupEmailTokenString\x1a\x1b.scheduler.SignupEmailTokenB)Z'mentipedia/go-backend/signup/grpc/stubsb\x06proto3"

var (
	file_signup_proto_rawDescOnce sync.Once
	file_signup_proto_rawDescData []byte
)

func file_signup_proto_rawDescGZIP() []byte {
	file_signup_proto_rawDescOnce.Do(func() {
		file_signup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signup_proto_rawDesc), len(file_signup_proto_rawDesc)))
	})
	return file_signup_proto_rawDescData
}

var file_signup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_signup_proto_goTypes = []any{
	(*SingupEmailTokenString)(nil), // 0: scheduler.SingupEmailTokenString
	(*SignupEmailToken)(nil),       // 1: scheduler.SignupEmailToken
	(*EmptyMsg)(nil),               // 2: scheduler.EmptyMsg
}
var file_signup_proto_depIdxs = []int32{
	0, // 0: scheduler.SignupService.DecodeAndVerify:input_type -> scheduler.SingupEmailTokenString
	1, // 1: scheduler.SignupService.DecodeAndVerify:output_type -> scheduler.SignupEmailToken
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signup_proto_init() }
func file_signup_proto_init() {
	if File_signup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signup_proto_rawDesc), len(file_signup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signup_proto_goTypes,
		DependencyIndexes: file_signup_proto_depIdxs,
		MessageInfos:      file_signup_proto_msgTypes,
	}.Build()
	File_signup_proto = out.File
	file_signup_proto_goTypes = nil
	file_signup_proto_depIdxs = nil
}
