// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: confirmationEmail.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupConfirmationEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// When the email will be sent, in seconds since Unix epoch
	DeadlineTimestampSeconds uint64 `protobuf:"varint,2,opt,name=deadline_timestamp_seconds,json=deadlineTimestampSeconds,proto3" json:"deadline_timestamp_seconds,omitempty"`
	// When did the server acknowledge the exam was properly submitted (without errors)
	ExamSubmissionDate uint64 `protobuf:"varint,3,opt,name=exam_submission_date,json=examSubmissionDate,proto3" json:"exam_submission_date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignupConfirmationEmailRequest) Reset() {
	*x = SignupConfirmationEmailRequest{}
	mi := &file_confirmationEmail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupConfirmationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupConfirmationEmailRequest) ProtoMessage() {}

func (x *SignupConfirmationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confirmationEmail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupConfirmationEmailRequest.ProtoReflect.Descriptor instead.
func (*SignupConfirmationEmailRequest) Descriptor() ([]byte, []int) {
	return file_confirmationEmail_proto_rawDescGZIP(), []int{0}
}

func (x *SignupConfirmationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupConfirmationEmailRequest) GetDeadlineTimestampSeconds() uint64 {
	if x != nil {
		return x.DeadlineTimestampSeconds
	}
	return 0
}

func (x *SignupConfirmationEmailRequest) GetExamSubmissionDate() uint64 {
	if x != nil {
		return x.ExamSubmissionDate
	}
	return 0
}

type EmptyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	mi := &file_confirmationEmail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_confirmationEmail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_confirmationEmail_proto_rawDescGZIP(), []int{1}
}

var File_confirmationEmail_proto protoreflect.FileDescriptor

const file_confirmationEmail_proto_rawDesc = "" +
	"\n" +
	"\x17confirmationEmail.proto\x12\tscheduler\"\xa6\x01\n" +
	"\x1eSignupConfirmationEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12<\n" +
	"\x1adeadline_timestamp_seconds\x18\x02 \x01(\x04R\x18deadlineTimestampSeconds\x120\n" +
	"\x14exam_submission_date\x18\x03 \x01(\x04R\x12examSubmissionDate\"\n" +
	"\n" +
	"\bEmptyMsg2\x83\x01\n" +
	"\x1eSignupConfirmationEmailService\x12a\n" +
	"\x1fRegisterSignupConfirmationEmail\x12).scheduler.SignupConfirmationEmailRequest\x1a\x13.scheduler.EmptyMsgB/Z-mentipedia/go-backend/signup/email/grpc/stubsb\x06proto3"

var (
	file_confirmationEmail_proto_rawDescOnce sync.Once
	file_confirmationEmail_proto_rawDescData []byte
)

func file_confirmationEmail_proto_rawDescGZIP() []byte {
	file_confirmationEmail_proto_rawDescOnce.Do(func() {
		file_confirmationEmail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confirmationEmail_proto_rawDesc), len(file_confirmationEmail_proto_rawDesc)))
	})
	return file_confirmationEmail_proto_rawDescData
}

var file_confirmationEmail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_confirmationEmail_proto_goTypes = []any{
	(*SignupConfirmationEmailRequest)(nil), // 0: scheduler.SignupConfirmationEmailRequest
	(*EmptyMsg)(nil),                       // 1: scheduler.EmptyMsg
}
var file_confirmationEmail_proto_depIdxs = []int32{
	0, // 0: scheduler.SignupConfirmationEmailService.RegisterSignupConfirmationEmail:input_type -> scheduler.SignupConfirmationEmailRequest
	1, // 1: scheduler.SignupConfirmationEmailService.RegisterSignupConfirmationEmail:output_type -> scheduler.EmptyMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_confirmationEmail_proto_init() }
func file_confirmationEmail_proto_init() {
	if File_confirmationEmail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confirmationEmail_proto_rawDesc), len(file_confirmationEmail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_confirmationEmail_proto_goTypes,
		DependencyIndexes: file_confirmationEmail_proto_depIdxs,
		MessageInfos:      file_confirmationEmail_proto_msgTypes,
	}.Build()
	File_confirmationEmail_proto = out.File
	file_confirmationEmail_proto_goTypes = nil
	file_confirmationEmail_proto_depIdxs = nil
}
