services:
  nextjs:
    image: node:24.0.1-bookworm-slim
    networks:
      - mentipedia_net
    volumes:
      - "/home/jorge/mentipedia/mentipedia-front:/mentipedia"
    working_dir: /mentipedia
    command: yarn next dev
    ports:
      - "10.172.172.1:10002:3000"


networks:
  mentipedia_net:
    driver: bridge
    ipam:
      driver: default
