name: mentipedia

services:
  backend-code-generator:
    user: ${UID}:${GID}
    build:
      context: ../go-backend/docker/generate
    volumes:
      - ../go-backend:/go-backend
      - ../common/interface:/common/interface
      