// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package logging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INFO-0]
	_ = x[WARN-1]
	_ = x[ERROR-2]
}

const _LogLevel_name = "INFOWARNERROR"

var _LogLevel_index = [...]uint8{0, 4, 8, 13}

func (i LogLevel) String() string {
	if i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
